### ISSUE TITLE
We can wind up with duplicate user_info entries for a given badge number???

### ISSUE THREAD

**Issue by jducoeur** [ArisiaInc/a21-remote-site#469]
We're getting a lot of errors in the log, of this form:
```
! @7ieaebcco - Internal server error, for (GET) [/api/user/96704] ->
 
play.api.UnexpectedException: Unexpected exception[UnexpectedContinuation$: Expected ResultSet exhaustion, but more rows were available.]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:355)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:261)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:429)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:421)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:453)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: doobie.util.invariant$UnexpectedContinuation$: Expected ResultSet exhaustion, but more rows were available.
	at doobie.util.invariant$UnexpectedContinuation$.<clinit>(invariant.scala:30)
	at doobie.hi.resultset$.$anonfun$getOption$1(resultset.scala:218)
	at cats.free.Free.step(Free.scala:53)
	at cats.free.Free.$anonfun$foldMap$1(Free.scala:153)
	at cats.data.KleisliFlatMap.$anonfun$tailRecM$2(Kleisli.scala:603)
	at cats.StackSafeMonad.tailRecM(StackSafeMonad.scala:15)
	at cats.StackSafeMonad.tailRecM$(StackSafeMonad.scala:15)
	at cats.effect.IOLowPriorityInstances$IOEffect.tailRecM(IO.scala:792)
	at cats.StackSafeMonad.$anonfun$tailRecM$1(StackSafeMonad.scala:16)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:142)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:359)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:380)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:323)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:139)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:359)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:380)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:323)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:35)
	... 7 common frames omitted
```
The reason for this is that we have two identical entries in the user_info table for member 96704.  Not clear what the code path is that allows that, but it isn't forbidden by Postgres, so it's plausible.

This is probably causing that person's Profile to fail to display; don't know if it has any other effect.

**Comment by jducoeur** [comment]
Don't know how we're getting into this state, but it's at least easy to prevent the error.

In principle, we should probably make the badge_number a unique index, but for now let's keep it safe and low-impact.

**Comment by jducoeur** [comment]
Ah -- the way we are getting into this state is apparently by people logging in with a space before or after their username.  So it *looks* the same, and CM apparently silently copes with that, but it allows a second username entry to show up.
